### ISSUE TITLE
testcase validate_printed_urls fail on macos

### ISSUE THREAD

**Issue by holymonson** [sigoden/dufs#135]
**Problem**

I'm trying to pack dufs on nixpkgs, but it fails some tests. Should it be fixed or just ignorable?

**Log**
```
❯ RUST_BACKTRACE=all cargo  t --test bind
    Finished test [unoptimized + debuginfo] target(s) in 0.37s
     Running tests/bind.rs (target/debug/deps/bind-259fb1b74927f5db)

running 6 tests
test bind_fails::case_1 ... ok
test bind_ipv4_ipv6::case_2 ... ok
test bind_ipv4_ipv6::case_1 ... ok
test bind_ipv4_ipv6::case_3 ... ok
Error: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv6(fd7a:115c:a1e0:ab12:4843:cd96:6269:7e7e)), port: Some(53921), path: "/", query: None, fragment: None }, source: TimedOut }
test validate_printed_urls::case_1 ... FAILED
Error: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv6(fd7a:115c:a1e0:ab12:4843:cd96:6269:7e7e)), port: Some(53927), path: "/prefix/", query: None, fragment: None }, source: TimedOut }
test validate_printed_urls::case_2 ... FAILED

failures:

---- validate_printed_urls::case_1 stdout ----
-------------- TEST START --------------
thread 'validate_printed_urls::case_1' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/test/src/lib.rs:184:5
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/panicking.rs:181:5
   4: test::assert_test_result
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/test/src/lib.rs:184:5
   5: bind::validate_printed_urls::case_1::{{closure}}
             at ./tests/bind.rs:48:1
   6: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- validate_printed_urls::case_2 stdout ----
-------------- TEST START --------------
thread 'validate_printed_urls::case_2' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/test/src/lib.rs:184:5
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/panicking.rs:181:5
   4: test::assert_test_result
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/test/src/lib.rs:184:5
   5: bind::validate_printed_urls::case_2::{{closure}}
             at ./tests/bind.rs:48:1
   6: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20220812-6672-194b8m/rustc-1.63.0-src/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    validate_printed_urls::case_1
    validate_printed_urls::case_2

test result: FAILED. 4 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 30.89s

error: test failed, to rerun pass '--test bind'

```

**Environment:**
 - Dufs version: rev 3b3ea71
 - Browser/Webdav Info: 
 - OS Info: macOS 12.6

**Comment by sigoden** [comment]
How can I reproduce this problem?

**Comment by holymonson** [comment]
> How can I reproduce this problem?

Simply run `cargo  test --test bind` on macos, but it seems you don't have the environment. I guess it fails the assertion below, do you get any hint why it's empty?https://github.com/sigoden/dufs/blob/3b3ea718d948a6ae387f6ab9ec20687c2380be3f/tests/bind.rs#L66-L78

**Comment by holymonson** [comment]
I think I found the reason, it's not thing to do with macos. I'm in VPN environment, some links are peer-to-peer. While dufs listening on all IPs, those IP won't response requests from local, so the testcase will fail with timeout.
